Repository boostercloud/booster, pull requests merged in 2020-11, with the labels that each got.

#476 Harder, Better, Faster, Stronger CLI integration tests
  .gitignore
  .vscode/launch.json
  packages/cli/src/commands/new/project.ts
  packages/framework-integration-tests/integration/cli/cli.command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.entity.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event-handler.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event.integration.ts
  packages/framework-integration-tests/integration/cli/cli.project.integration.ts
  packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts
  packages/framework-integration-tests/integration/cli/cli.scheduled-command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.type.integration.ts
  packages/framework-integration-tests/integration/cli/setup.ts
  packages/framework-integration-tests/integration/end-to-end/cart.integration.ts
  packages/framework-integration-tests/integration/fixtures/cart-demo/package.json
  packages/framework-integration-tests/integration/fixtures/cart-demo/src/config/config.ts
  packages/framework-integration-tests/integration/helper/fileHelper.ts
  packages/framework-integration-tests/integration/helper/sleep.ts
  packages/framework-integration-tests/integration/providers/aws/deployment/setup.ts
  packages/framework-integration-tests/integration/providers/aws/functionality/scheduled-commands.integration.ts
  packages/framework-integration-tests/integration/providers/aws/utils.ts
  packages/framework-integration-tests/integration/providers/local/setup.ts
  packages/framework-integration-tests/src/entities/cart.ts
  packages/framework-integration-tests/src/events/cart-checked.ts
  packages/framework-integration-tests/src/read-models/cart-read-model.ts
  packages/framework-integration-tests/src/scheduled-commands/check-cart-count.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted, size: L

#479 Reworked the way environments are managed by the CLI
  packages/cli/src/commands/deploy.ts
  packages/cli/src/commands/nuke.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/common/environment.ts
  packages/cli/src/services/config-service.ts
  packages/cli/test/commands/deploy.test.ts
  packages/cli/test/commands/nuke.test.ts
  packages/cli/test/commands/start.test.ts
  packages/cli/test/services/config-service.test.ts
  packages/framework-core/src/booster.ts
  packages/framework-core/test/booster.test.ts
  packages/framework-types/src/booster-app.ts
  packages/framework-types/src/config.ts
Labels: enhancement, hacktoberfest-accepted

#414 Infrastructure rockets: the way to extend Booster infrastructure in AWS. (Also transformed the static site deployment feature into the first rocket)
  .vscode/launch.json
  docs/README.md
  lerna.json
  package.json
  packages/cli/src/templates/project/config-ts.ts
  packages/framework-integration-tests/integration/cli/cli.command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.entity.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event-handler.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event.integration.ts
  packages/framework-integration-tests/integration/cli/cli.project.integration.ts
  packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts
  packages/framework-integration-tests/integration/cli/cli.scheduled-command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.type.integration.ts
  packages/framework-integration-tests/integration/cli/setup.ts
  packages/framework-integration-tests/integration/fixtures/cart-demo/src/config/config.ts
  packages/framework-integration-tests/integration/helper/depsHelper.ts
  packages/framework-integration-tests/integration/helper/fileHelper.ts
  packages/framework-integration-tests/integration/providers/local/auth.integration.ts
  packages/framework-integration-tests/integration/providers/local/commands.integration.ts
  packages/framework-integration-tests/integration/providers/local/constants.ts
  packages/framework-integration-tests/integration/providers/local/setup.ts
  packages/framework-integration-tests/src/config/config.ts
  packages/framework-integration-tests/src/deploy.ts
  packages/framework-provider-aws-infrastructure/src/index.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/deploy.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/index.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/nuke.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/s3utils.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stack-tools.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/static-website-stack.ts
  packages/framework-provider-aws-infrastructure/src/rockets/infrastructure-rocket.ts
  packages/framework-provider-aws-infrastructure/src/rockets/rocket-utils.ts
  packages/framework-provider-aws-infrastructure/test/index.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure-rocket.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/deploy.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/nuke.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stack-tools.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/application-stack.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/static-website-stack.test.ts
  packages/framework-provider-aws/src/index.ts
  packages/framework-provider-aws/test/index.test.ts
  packages/framework-provider-azure/src/index.ts
  packages/framework-provider-kubernetes/src/index.ts
  packages/framework-provider-local-infrastructure/src/index.ts
  packages/framework-provider-local/src/index.ts
  packages/framework-types/src/config.ts
  packages/framework-types/src/index.ts
  packages/framework-types/src/rocket-descriptor.ts
  packages/rocket-static-sites-aws-infrastructure/.eslintignore
  packages/rocket-static-sites-aws-infrastructure/.mocharc.yml
  packages/rocket-static-sites-aws-infrastructure/package.json
  packages/rocket-static-sites-aws-infrastructure/src/index.ts
  packages/rocket-static-sites-aws-infrastructure/src/static-website-stack.ts
  packages/rocket-static-sites-aws-infrastructure/test/static-website-stack.test.ts
  packages/rocket-static-sites-aws-infrastructure/tsconfig.eslint.json
  packages/rocket-static-sites-aws-infrastructure/tsconfig.json
Labels: hacktoberfest-accepted

#477 Feature: Use JWT authorization tokens to grant access
  docs/README.md
  packages/framework-core/package.json
  packages/framework-core/src/booster-auth.ts
  packages/framework-core/src/booster-graphql-dispatcher.ts
  packages/framework-core/src/services/graphql/websocket-protocol/graphql-websocket-protocol.ts
  packages/framework-core/test/booster-auth.test.ts
  packages/framework-core/test/booster-graphql-dispatcher.test.ts
  packages/framework-core/test/services/graphql/websocket-protocol/graphql-websocket-protocol.test.ts
  packages/framework-integration-tests/integration/end-to-end/cart.integration.ts
  packages/framework-integration-tests/integration/providers/aws/functionality/auth.integration.ts
  packages/framework-integration-tests/integration/providers/aws/functionality/event-handlers.integration.ts
  packages/framework-integration-tests/integration/providers/aws/utils.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/params.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/api-stack-velocity-templates.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/auth-stack.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/graphql-stack.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/api-stack-velocity-templates.test.ts
  packages/framework-provider-aws/src/index.ts
  packages/framework-provider-aws/src/library/graphql-adapter.ts
  packages/framework-provider-aws/test/library/graphql-adapter.test.ts
  packages/framework-types/src/config.ts
  packages/framework-types/src/envelope.ts
  packages/framework-types/src/provider.ts
  yarn.lock
Labels: enhancement, size: M

#473 Local Provider - Read Models Simple Queries
  packages/framework-integration-tests/integration/providers/local/auth.integration.ts
  packages/framework-integration-tests/integration/providers/local/commands.integration.ts
  packages/framework-integration-tests/integration/providers/local/read-models.integration.ts
  packages/framework-integration-tests/integration/providers/local/utils.ts
  packages/framework-provider-local/src/index.ts
  packages/framework-provider-local/src/library/events-adapter.ts
  packages/framework-provider-local/src/library/read-model-adapter.ts
  packages/framework-provider-local/src/paths.ts
  packages/framework-provider-local/src/services/index.ts
  packages/framework-provider-local/src/services/read-model-registry.ts
  packages/framework-provider-local/test/helpers/event-helper.ts
  packages/framework-provider-local/test/helpers/read-model-helper.ts
  packages/framework-provider-local/test/library/read-model-adapter.test.ts
  packages/framework-provider-local/test/services/read-model-registry.test.ts
Labels: hacktoberfest-accepted

#495 Fixed local integration tests
  packages/framework-integration-tests/integration/providers/local/read-models.integration.ts
Labels: bug
