Repository boostercloud/booster, pull requests merged in 2021-01, with the labels that each got.

#520 docs: include branch naming conventions section
  CONTRIBUTING.md
Labels: documentation

#545 Change to NPM
  .eslintrc.js
  .github/workflows/integration-tests.yml
  .vscode/launch.json
  CONTRIBUTING.md
  docs/README.md
  lerna.json
  package-lock.json
  package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/services/config-service.ts
  packages/cli/src/services/dependencies.ts
  packages/cli/test/services/dependencies.test.ts
  packages/framework-core/package-lock.json
  packages/framework-core/package.json
  packages/framework-core/src/booster.ts
  packages/framework-core/test/booster-command-dispatcher.test.ts
  packages/framework-integration-tests/integration/cli/cli.project.integration.ts
  packages/framework-integration-tests/integration/cli/setup.ts
  packages/framework-integration-tests/integration/helper/depsHelper.ts
  packages/framework-integration-tests/integration/providers/aws/deploy.ts
  packages/framework-integration-tests/integration/providers/aws/deployment/setup.ts
  packages/framework-integration-tests/integration/providers/aws/nuke/setup.ts
  packages/framework-integration-tests/integration/providers/local/setup.ts
  packages/framework-integration-tests/package-lock.json
  packages/framework-integration-tests/package.json
  packages/framework-provider-aws-infrastructure/package-lock.json
  packages/framework-provider-aws-infrastructure/package.json
  packages/framework-provider-aws/package-lock.json
  packages/framework-provider-aws/package.json
  packages/framework-provider-aws/src/index.ts
  packages/framework-provider-aws/test/index.test.ts
  packages/framework-provider-azure-infrastructure/package.json
  packages/framework-provider-azure/package.json
  packages/framework-provider-kubernetes-infrastructure/package.json
  packages/framework-provider-local-infrastructure/package-lock.json
  packages/framework-provider-local-infrastructure/package.json
  packages/framework-provider-local/package-lock.json
  packages/framework-provider-local/package.json
  packages/framework-types/package-lock.json
  packages/framework-types/package.json
  packages/framework-types/src/concepts/uuid.ts
  packages/framework-types/src/searcher.ts
  packages/rocket-static-sites-aws-infrastructure/README.md
  packages/rocket-static-sites-aws-infrastructure/package.json
  packages/rocket-static-sites-aws-infrastructure/test/expect.ts
  packages/rocket-static-sites-aws-infrastructure/test/static-website-stack.test.ts
  yarn.lock
Labels: dependencies, enhancement, size: L

#546 Remainders and fixes from the previous "yarn to npm" spike
  CONTRIBUTING.md
  docs/README.md
  package.json
  packages/framework-core/test/booster-command-dispatcher.test.ts
  packages/framework-provider-aws/test/library/subscription-adapter.test.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts
  packages/framework-provider-kubernetes-infrastructure/src/infrastructure/utils.ts
  packages/framework-types/src/concepts/uuid.ts
Labels: enhancement

#555 541 refactor GraphQLGenerator class
  packages/framework-core/src/booster-graphql-dispatcher.ts
  packages/framework-core/src/booster-subscribers-notifier.ts
  packages/framework-core/src/services/graphql/graphql-generator.ts
  packages/framework-core/test/services/graphql/graphql-generator.test.ts
Labels: enhancement

#570 Fix for lambda size problem (and probably others related to dependencies)
  .gitignore
  package-lock.json
  packages/cli/package.json
  packages/cli/src/commands/deploy.ts
  packages/cli/src/commands/new/command.ts
  packages/cli/src/commands/new/entity.ts
  packages/cli/src/commands/new/event-handler.ts
  packages/cli/src/commands/new/event.ts
  packages/cli/src/commands/new/read-model.ts
  packages/cli/src/commands/new/scheduled-command.ts
  packages/cli/src/commands/new/type.ts
  packages/cli/src/commands/nuke.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/common/sandbox.ts
  packages/cli/src/services/config-service.ts
  packages/cli/src/services/dependencies.ts
  packages/cli/src/services/project-checker.ts
  packages/cli/src/templates/project/index-ts.ts
  packages/cli/src/templates/project/package-json.ts
  packages/cli/test/commands/deploy.test.ts
  packages/cli/test/commands/new.test.ts
  packages/cli/test/services/config-service.test.ts
  packages/cli/test/services/dependencies.test.ts
  packages/framework-core/src/booster.ts
  packages/framework-core/src/importer.ts
  packages/framework-core/test/booster.test.ts
  packages/framework-core/test/importer.test.ts
  packages/framework-integration-tests/integration/cli/cli.command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.entity.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event-handler.integration.ts
  packages/framework-integration-tests/integration/cli/cli.event.integration.ts
  packages/framework-integration-tests/integration/cli/cli.project.integration.ts
  packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts
  packages/framework-integration-tests/integration/cli/cli.scheduled-command.integration.ts
  packages/framework-integration-tests/integration/cli/cli.type.integration.ts
  packages/framework-integration-tests/integration/fixtures/cart-demo/src/index.ts
  packages/framework-integration-tests/integration/helper/depsHelper.ts
  packages/framework-integration-tests/integration/helper/fileHelper.ts
  packages/framework-integration-tests/integration/providers/aws/deployment/setup.ts
  packages/framework-integration-tests/integration/providers/aws/nuke/setup.ts
  packages/framework-integration-tests/integration/providers/local/setup.ts
  packages/framework-integration-tests/package.json
  packages/framework-integration-tests/src/entities/payment.ts
  packages/framework-integration-tests/src/index.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/deploy.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stack-tools.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/application-stack.test.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/read-models-stack.test.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/setup.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/stacks/api-stack.ts
  packages/framework-provider-local-infrastructure/test/controllers/graphql.test.ts
  packages/framework-provider-local/src/library/events-adapter.ts
  packages/framework-provider-local/test/helpers/event-helper.ts
  packages/framework-provider-local/test/helpers/read-model-helper.ts
  packages/framework-provider-local/test/library/events-adapter.test.ts
  packages/framework-types/package.json
  packages/framework-types/src/booster-app.ts
  packages/framework-types/src/config.ts
  packages/framework-types/src/graphql-websocket-messages.ts
Labels: bug, dependencies

#562 Added some code guidelines
  CONTRIBUTING.md
Labels: documentation
