Repository boostercloud/booster, pull requests merged in 2021-03, with the labels that each got.

#671 fix to allows service to get the ip from hostname
  packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts
Labels: multicloud

#670 fix(azure): Azure cosmosDB error at deployment
  packages/framework-core/test/helpers/promises.test.ts
  packages/framework-provider-azure/src/index.ts
Labels: multicloud

#697 Add azure as option in Booster CLI when creating new Booster project
  packages/cli/src/commands/new/project.ts
  packages/cli/src/common/provider.ts
Labels: multicloud

#698 Fix azure provider infra
  packages/framework-provider-azure-infrastructure/src/infrastructure/arm-templates/cosmos-db-account.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/index.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts
Labels: multicloud

#722 Documentation: Booster infrastructure advantages
  docs/README.md
Labels: documentation

#725 Documentation: Small improvements in "Booster architecture" section
  docs/README.md
Labels: documentation

#732 Documentation: Small improvements in the "GraphQL API" section
  docs/README.md
Labels: documentation

#737 Documentation: Small improvements in the "Debugging and testing Booster applications" section.
  docs/README.md
Labels: documentation

#741 add searcher-adapter for redis db
  packages/framework-provider-kubernetes/src/index.ts
  packages/framework-provider-kubernetes/src/library/searcher-adapter.ts
Labels: kubernetes

#734 Documentation: Small improvements in the "Going deeper with Booster" section
  docs/README.md
Labels: documentation

#761 Improve installing nodejs section
  docs/README.md
Labels: documentation
