Repository boostercloud/booster, pull requests merged in 2021-02, with the labels that each got.

#560 doc: Add comment in contributing file indicating that Node v12.19 is …
  CONTRIBUTING.md
Labels: documentation

#581 feature: Print the full GraphQL endpoint after a successful deploy
  docs/README.md
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
Labels: enhancement

#526 Tests/502 cli validations, unit tests, fix double quote bug
  .gitignore
  packages/cli/src/services/generator/target/parsing.ts
  packages/cli/src/services/user-prompt.ts
  packages/cli/test/commands/deploy.test.ts
  packages/cli/test/commands/new.test.ts
  packages/cli/test/commands/new/command.test.ts
  packages/cli/test/commands/new/entity.test.ts
  packages/cli/test/commands/new/event-handler.test.ts
  packages/cli/test/commands/new/event.test.ts
  packages/cli/test/commands/new/project.test.ts
  packages/cli/test/commands/new/read-model.test.ts
  packages/cli/test/commands/new/scheduled-command.test.ts
  packages/cli/test/commands/new/type.test.ts
  packages/cli/test/commands/nuke.test.ts
  packages/cli/test/commands/start.test.ts
  packages/cli/test/fixtures/mock_project/src/index.ts
  packages/cli/test/fixtures/mock_project/tsconfig.json
  packages/cli/test/fixtures/mock_project_bad_index/src/index.ts
  packages/cli/test/fixtures/mock_project_bad_index/tsconfig.json
  packages/cli/test/services/environment.test.ts
  packages/cli/test/services/generator.test.ts
  packages/cli/test/services/generator/target/parsing.test.ts
  packages/cli/test/services/logger.test.ts
  packages/cli/test/services/project-checker.test.ts
  packages/cli/test/services/project-initializer.test.ts
  packages/cli/test/services/user-prompt.test.ts
Labels: enhancement, good first issue, size: L, testing

#595 Doc: Update contributing file
  CONTRIBUTING.md
Labels: documentation

#607 Fix: Reference error in publish GitHub action script
  .github/workflows/publish.yml
Labels: bug

#475 [WIP] feat(cli): ask to override files
  docs/README.md
  packages/cli/src/commands/new/project.ts
  packages/cli/src/services/generator.ts
  packages/cli/src/services/generator/target/index.ts
  packages/cli/src/services/project-checker.ts
  packages/cli/src/services/project-initializer.ts
  packages/cli/src/services/user-prompt.ts
  packages/cli/test/services/generator.test.ts
  packages/cli/test/services/project-checker.test.ts
  packages/cli/test/services/user-prompt.test.ts
  packages/framework-integration-tests/integration/cli/cli.event.integration.ts
  packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts
Labels: booster cli, enhancement, size: M

#573 New GraphQL filters
  docs/README.md
  packages/framework-core/src/booster-read-model-dispatcher.ts
  packages/framework-core/src/services/graphql/graphql-generator.ts
  packages/framework-core/src/services/pub-sub/read-model-pub-sub.ts
  packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts
  packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts
  packages/framework-provider-aws/src/library/searcher-adapter.ts
  packages/framework-provider-aws/test/library/searcher-adapter.test.ts
  packages/framework-provider-azure/src/library/searcher-adapter.ts
  packages/framework-provider-azure/test/library/searcher-adapter.test.ts
  packages/framework-provider-local/src/index.ts
  packages/framework-provider-local/src/library/read-model-adapter.ts
  packages/framework-provider-local/src/library/searcher-adapter.ts
  packages/framework-types/src/envelope.ts
  packages/framework-types/src/provider.ts
  packages/framework-types/src/searcher.ts
Labels: package: aws, package: core, size: L
