Repository boostercloud/booster, pull requests merged in 2022-12, with the labels that each got.

#1182 Add port to mountStack for local rockets
  packages/framework-provider-local-infrastructure/src/index.ts
  packages/framework-provider-local-infrastructure/src/infrastructure-rocket.ts
Labels: do not merge

#1263 [Issue #1196] Change default behaviour of new:project
  common/changes/@boostercloud/framework-core/fix-1196_remove-params-from-new-project_2022-12-14-13-08.json
  docs/chapters/02_getting-started.md
  packages/cli/src/commands/new/project.ts
  packages/cli/src/services/project-initializer.ts
  packages/cli/test/commands/new/project.test.ts
  packages/cli/test/services/project-initializer.test.ts
Labels: booster cli, dev-experience

#1283 Documentation: Minor improvements in format and content to the "Get Started" section
  common/config/rush/pnpm-lock.yaml
  website/docs/01_introduction.md
  website/docs/02_getting-started/coding.mdx
Labels: documentation

#1291 Improved migrations documentation
  website/docs/03_features/03_data-migrations.md
Labels: documentation
