Repository boostercloud/booster, pull requests merged in 2023-02, with the labels that each got.

#1186 Support multiple rockets
  common/changes/@boostercloud/framework-core/support_many_rockets_2023-02-13-11-39.json
  common/config/rush/pnpm-lock.yaml
  packages/framework-core/src/booster-rocket-dispatcher.ts
  packages/framework-provider-aws/src/index.ts
  packages/framework-provider-aws/src/library/rocket-adapter.ts
  packages/framework-provider-aws/src/setup.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/index.ts
  packages/framework-provider-azure-infrastructure/src/infrastructure/rockets/rocket-builder.ts
  packages/framework-provider-azure/src/index.ts
  packages/framework-provider-azure/src/library/rocket-adapter.ts
  packages/framework-provider-kubernetes/src/index.ts
  packages/framework-provider-kubernetes/src/library/rocket-adapter.ts
  packages/framework-provider-local/src/index.ts
  packages/framework-provider-local/src/library/rocket-adapter.ts
  packages/framework-types/src/provider.ts
  packages/framework-types/src/rockets.ts
Labels: do not merge

#1331 Separated event from snapshot storage and started using the value `snapshottedEventCreatedAt` in snapshots to initialize the database sort key.
  packages/framework-core/src/booster-data-migrations.ts
  packages/framework-core/src/booster-event-dispatcher.ts
  packages/framework-core/src/booster-register-handler.ts
  packages/framework-core/src/schema-migrator.ts
  packages/framework-core/src/services/event-store.ts
  packages/framework-core/src/services/raw-events-parser.ts
  packages/framework-core/src/services/read-model-store.ts
  packages/framework-core/test/booster-event-dispatcher.test.ts
  packages/framework-core/test/booster-global-error-dispatcher.test.ts
  packages/framework-core/test/booster-read-model-reader.test.ts
  packages/framework-core/test/booster-register-handler.test.ts
  packages/framework-core/test/services/event-store.test.ts
  packages/framework-core/test/services/raw-events-parser.test.ts
  packages/framework-core/test/services/read-model-store.test.ts
  packages/framework-provider-aws/src/index.ts
  packages/framework-provider-aws/src/library/events-adapter.ts
  packages/framework-provider-aws/src/library/keys-helper.ts
  packages/framework-provider-aws/src/setup.ts
  packages/framework-provider-aws/test/index.test.ts
  packages/framework-provider-aws/test/library/events-adapter.test.ts
  packages/framework-provider-aws/test/library/events-search-adapter.test.ts
  packages/framework-provider-aws/test/library/partition-keys.test.ts
  packages/framework-provider-azure/src/index.ts
  packages/framework-provider-azure/src/library/events-adapter.ts
  packages/framework-provider-azure/src/library/partition-keys.ts
  packages/framework-provider-azure/test/library/events-adapter.test.ts
  packages/framework-provider-kubernetes/src/index.ts
  packages/framework-provider-kubernetes/src/library/events-adapter.ts
  packages/framework-provider-kubernetes/src/services/event-registry.ts
  packages/framework-provider-local/.vscode/launch.json
  packages/framework-provider-local/src/index.ts
  packages/framework-provider-local/src/library/events-adapter.ts
  packages/framework-provider-local/src/services/event-registry.ts
  packages/framework-provider-local/test/helpers/event-helper.ts
  packages/framework-provider-local/test/library/events-adapter.test.ts
  packages/framework-provider-local/test/services/event-registry.test.ts
  packages/framework-types/src/concepts/global-error-handler-metadata.ts
  packages/framework-types/src/envelope.ts
  packages/framework-types/src/errors/snapshot-persist-handler-global-error.ts
  packages/framework-types/src/provider.ts
Labels: size: XL, package:core, refactor, provider:multicloud

#1357 Added Fathom Analytics support to the documentation
  website/docs/02_getting-started/coding.mdx
  website/docs/02_getting-started/installation.mdx
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/sidebars.js
  website/src/components/CustomLink.jsx
  website/src/components/CustomSidebarItem.jsx
  website/src/theme/DocSidebarItem/index.js
  website/src/theme/NavbarItem/NavbarNavLink.js
Labels: documentation
