Repository boostercloud/booster, pull requests merged in 2023-01, with the labels that each got.

#1292 [WIP] Start dispatching PR commands on CICD
  .github/actions/test-integration-run-one/action.yml
  .github/cache-version.yml
  .github/workflows/wf_cicd_commands.yml
  .github/workflows/wf_test-integration.yml
  common/config/rush/pnpm-lock.yaml
Labels: do not merge

#1308 Added documentation for nested queries using getters
  .github/workflows/wf_check-changes.yml
  .github/workflows/wf_check-lint.yml
  .github/workflows/wf_publish-npm.yml
  .github/workflows/wf_test-unit.yml
  website/docs/03_architecture/06_read-model.mdx
Labels: documentation, dev-experience

#1310 Implemented a fallback to check the existence of a 'compile' command in the project package.json file for backwards compatibility
  .vscode/launch.json
  booster.code-workspace
  common/changes/@boostercloud/framework-core/fix-issue-1307-backwards-compatibility-with-projects-that-define-a-compile-script_2023-01-23-20-32.json
  common/config/rush/pnpm-lock.yaml
  packages/cli/src/services/config-service.ts
  packages/cli/src/services/file-system/index.ts
  packages/cli/src/services/file-system/live.impl.ts
  packages/cli/src/services/package-manager/common.ts
  packages/cli/src/services/package-manager/index.ts
  packages/cli/src/services/package-manager/rush.impl.ts
  packages/cli/test/services/config-service.test.ts
  packages/cli/test/services/file-system/test.impl.ts
  packages/cli/test/services/package-manager/npm.test.ts
  packages/cli/test/services/package-manager/pnpm.test.ts
  packages/cli/test/services/package-manager/rush.test.ts
  packages/cli/test/services/package-manager/test.impl.ts
  packages/cli/test/services/package-manager/yarn.test.ts
  packages/framework-integration-tests/integration/provider-unaware/cli/cli.build.integration.ts
Labels: bug 🐞, dev-experience, ci/cd
